"""Puerto: UserRepository."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from evidence_ai.domain.entities import User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_oauth(self, provider: str, subject: str) -> User | None: ...
    async def create(self, user: User) -> User: ...
    async def update(self, user: User) -> User: ...
